---
title: "Лекция 1. Същност на икономическата наука"
author: "Александър Косулиев"
date: "September 14, 2015"
output: html_document
---

# Лекция 1. Същност на икономическата наука

## 1. Обект и клонове на икономическата наука

Обект на икономическата наука е икономическата система. Икономическата система представлява „съвкупност от взаимнообуславящи се производствени процеси, а всеки производствен процес - като въздействие от страна на човека върху природни вещи и процеси, което ги превръща в потребителни стойности“. Икономическата система може да бъде обект на изучаване и от други науки. Икономиката поставя акцента върху отношенията между производствените процеси, чрез които се изразяват отношения между хора, действащи като субекти на икономическата дейност с определено поведение и интереси.

* Клоновете на икономическата наука могат да се обособят в четири големи групи:
  * Първата група изучава икономиката на различни нейни равнища (напр. общата икономическа теория);
  * Втората група включва функционалните икономически науки, които пронизват всички равнища (счетоводство, финанси, икономика на труда и др.);
  * Третата група са конкретни, изучаващи отраслите в икономиката (напр. икономика на туризма);
  * Четвъртата група включва исторически икономически дисциплини като стопанска история.

## 2. Определение и функции на общата икономическа теория

* Предмет на общата икономическата теория - начина на развитие на отделните общества и как те използват ограничените ресурси, с които разполагат;
  * Понятието оскъдност е ключово за цялата икономическа наука. Недостигът означава невъзможността на наличните ресурси да задоволят изцяло нащите нужди и желания;
  * Лайнъл Робинс: _„Икономическата наука изследва човешкото поведение като взаимоотношение между целите и оскъдните средства, които имат алтернативна употреба“_;
* Основни функции на икономическата теория - познавателна, практическа и методологическа

## 3. Методи и проблеми при изучаване на икономическата система

* Методи
  * Абстрактно-логически (дедукция и индукция)
  * Сравнителен метод
  * Статистически методи
  * Математически методи
* Проблеми
  * Хората са непостоянни
  * Икономистите невинаги са обективни и безпристрастни
  * Трудно се провеждат контролирани експерименти
  * Понякога не е възможно да се правят точни измервания
* Използват се опростени схеми или модели. Имат отношение към частни зависимости.
  * „ceteris paribus“ - при равни други условия
* Теория - обозначава по-общи и цялостни възгледи за икономическите зависимости

## 4. Микроикономика и макроикономика

* Микроикономиката е икономическият анализ на поведението на микроединицте в икономическата система - домакинствата и фирмите. Този раздел се занимава с изследване на три основни въпроса - потребителското търсене, производствените решения, ценообразуването и пазарното поведение;
* Макроикономиката се интересува от националното стопанство като цяло. Тя изследва микроединиците в тяхната обвързаност.

## 5. Позитивна и нормативна теория

* Позитивната икономическа теория се занимава с това, което е било, което е или което ще бъде. Позитивните твърдения изтъкват факти;
* Нормативната икономическа теория се занимава с това, което трябва да бъде.

## 6. Еволюция на икономическата теория

* Меркантилизъм
* Класическа школа
* Марксистка политическа икономия
* Неокласическа икономическа теория
* Кейнсианска икономическа теория
* Неолиберализъм



```{r, echo = FALSE}
stolowe <- c(0, 12, 22, 30, 36, 40, 42, 43)
masi <- c(14, 12, 10, 8, 6, 4, 2, 0)

ppf.df <- data.frame(stolowe, masi)
row.names(ppf.df) <- LETTERS[seq(1:8)]
colnames(ppf.df) <- c("столове", "маси")

```

точка|A|B|C|D|E|F|G|H
столове|0|12|22|30|36|40|42|43
маси|14|12|10|8|6|4|2|0
