---
title: "Намеса на държавата в икономиката"
author: "Александър Косулиев"
date: "28.11.2015"
output: 
  pdf_document: 
    latex_engine: xelatex
    toc: yes
    toc_depth: 3
mainfont: Liberation Serif
sansfont: Liberation Sans
monofont: Liberation Mono
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(fig.width = 8, fig.height = 6,
                      fig.path = "figure/",
                      #dev='cairo_pdf',
                      echo = FALSE, warning = FALSE, 
                      message = FALSE)
```

# Намеса на държавата в икономиката

## 1. Балансът между икономическата дейност на частния и обществения сектор

В темите досега показахме способността на пазарния механизъм да
се самоорганизира и саморегулира, като насочва ресурсите към
онази употреба, която в най-голяма степен съответства на нуждите
на хората, претеглени през тяхната покупателна способност. С
оглед на ефективното действие на пазарния механизъм, необходима
ли е изобщо държавна намеса? Между икономистите съществува почти
пълен консенсус, че такава намеса е необходима, но са големи
споровете относно границата, до която тя се разпростира.
Без съмнение е, че държавата трябва да изпълнява ролята на гарант за
правата на собствеността и спазването на договорните задължения.
Тоест, да налага "правилата на играта", които позволяват
нормалното функциониране на пазарната система. Но има много и
различни мнения по отношение на държавата като потребител и
особено като производител на блага. Други спорни точки са
свързани с преразпределителната ѝ функция на вече произведени
блага и с нейната роля като регулатор на стопанската
дейност. Може да се каже, че намесата на държавата и нейните
институции в стопанската дейност като потребител, производител и
регулатор формира обществения сектор.

## 2. Пазарни провали

Основанията за държавна намеса често се оправдават със
съществуването на т.нар. "пазарни провали". Пазарните провали се
наблюдават тогава, когато пазарът не е в състояние да
достави изобщо благата, които търси населението, или ги доставя,
но в количество, различно от желаното. Те се наблюдават, защото
не са изпълнени условията за нормалното функциониране на пазарния
механизъм.

### 2.1. Обществени блага

Повечето блага, които хората потребяват, са частни. Те са частни
в един технически и особен смисъл, който придават икономистите на
тази дума в контекста на фразата "частни блага". "Частните блага"
в повечето случаи са частни и в смисъла, който има тази дума и в
разговорната реч - че са частна собственост. Но е напълно
възможно някои от тези блага да са публична собственост. Например
пейките в парка са частни блага, но са публична собственост.
Това, което характеризира частните блага, е възможността за
тяхната отчуждаемост, което е свързано с факта, че те са
*конкурентни в потреблението*. Конкурентността в потреблението
означава, че притежанието и/или използването на дадено благо от
някого намалява наличността му на разположение на други хора, в 
повечето случаи до такава степен, че те не могат да го използват
изобщо. Ако Иван изпие чаша със сок, този сок вече става
недостъпен за Мария. Аналогично, ако Иван има пейка в двора си,
тази пейка не може да бъде по същото време в двора на къщата на
Мария. Поради тази причина пейката е частно благо. При частното
благо собственикът има възможност за изключване на други
потребители от достъп до него, като за много от тези блага
изключването следва автоматично и понякога необратимо от самия
процес на потреблението. 

За разлика от пейката в парка обаче, самият парк е (с известна
условност) обществено благо. Възможно е по едно и също време в
парка да се разхождат както Иван, така и Мария и още много други
хора, без използването на парка като място за разходка от едни да
се отразява на възможността на други хора да го ползват
пълноценно. Едната от характеристиките на обществените блага е
тяхната *неконкурентност в потреблението*. Но това не е
достатъчно, за да бъде едно благо обществено. Друга негова
характеристика е *невъзможността за изключване на потребители*.
Затова паркът е даден като пример за такова благо с известна
условност. Не е невъзможно паркът да бъде ограден и влизането в
него да става срещу входна такса. По-подходящ пример за
обществено благо би било уличното осветление, защото е невъзможно
да се ползва само от хората, които са платили за него.

Заради характеристиките си неконкурентност в потреблението и
невъзможност за изключване обществените блага се предлагат от
държавата, но не всяко благо, което се предлага от държавата, е
обществено в този смисъл на думата. Както вече бе споменато,
държавата може да бъде собственик и на частни блага. При
обществените блага в крайна сметка се стига до там, че ако се
предлагат изобщо, те се предлагат от държавата. За частните фирми
това е неизгодно, защото, при невъзможност за изключване на
потребители, за всеки отделен потребител е рационално да остави
някой друг да плати за благото, а той самият да го ползва
безплатно. Тъй като това прилича много на поведението на
пътниците без билети в градския транспорт, в икономическата
теория тези хора също се наричат по този начин или "гратисчии".
Проблемът с гратисчиите при предлагането на обществени блага е,
че те обикновено са твърде много и фирмите не успяват да покрият
разходите си. Това прави тези блага непривлекателни за частни
производители, които работят с цел печалба. Докато при частните
блага отделният потребител има стимул да разкрие истинските си
предпочитания, защото в противен случай може да остане без
необходимото му благо, при неконурентните в потреблението блага
той може да се възползва от тях, стига да има някой друг, който е
склонен да заплати за тяхното създаване.  

В крайна сметка се стига до държавна намеса, като финансирането
на тези блага се осигурява от данъци, тоест чрез принудително
плащане - нещо, което е в състояние да направи само държавата. 


### 2.2. Извънпазарни ефекти

Извънпазарните ефекти (наричани още външни) се наблюдават тогава,
когато една част от разходите или ползите, произтичащи от дадена
дейност, не се поемат изцяло от страните, които са преки
участници в нея. Разграничават се отрицателни и положителни
извънпазарни ефекти. 

*Отрицателните извънпазарни ефекти* се
наблюдават, когато част от разходите, съпътстващи дадена дейност,
се поемат от страна, която няма пряко отношение към дейността.
Тогава предлагането на произвежданата стока или услуга превишава
оптималното количество, което се търси от нея. Пример за такъв
ефект е дейността на предприятие, което замърсява въздуха.
Предприятието може да произвежда и продава продукцията си на
клиенти, които по никакъв начин не търпят последиците от това
замърсяване. Тогава една част от разходите се заплащат от хората,
живеещи в околността му, под формата на по-ниско качество на
живот заради мръсния въздух. Ако предприятието сложи
пречиствателна станция тези разходи ще се интернализират, тоест
ще се поемат от някой от участниците в транзакцията. Заради
по-високите производствени разходи след поставянето на
пречиствателната инсталация или предприятието ще трябва да приеме
по-ниска печалба, или неговите клиенти ще трябва да приемат
по-висока цена. И в двата случая обаче (или при комбинация от
тях) равновесното количество от произведеното продукция след
поставянето на инсталацията ще бъде по-малко и в съответствие със
социалния оптимум. Проблемът със съществуването на отрицателни
извънпазарни ефекти е, че пазарът не създава необходимите стимули
за интернализирането на социалните разходи от страна на
участниците, заради което е необходимо да се намеси държавата
като принуди участниците да коригират производството и
потреблението или като обложи тази дейност с допълнителни данъци,
или като предприеме регулаторни мерки за отстраняването на
външните ефекти и интернализирането на техните разходи.

*Положителните извънпазарни ефекти* се наблюдават, когато една
част от ползите, съпътстващи дадена дейност, не се поемат само от
участниците, а и от трета страна, която няма пряко отношение към
нея. Пример за това е ваксинирането, тъй като при него ползите са
не само за производителя на ваксината, който печели от нейната
продажба, нито пък за ваксинирания, за когото са директните ползи
от употребата ѝ. От ваксинирането печелят и трети страни, тъй
като вероятността за зараза за тях намалява с увеличаването на
броя на ваксинираните. При наличието на положителни извънпазарни
ефекти държавата обикновено субсидира производствата на стоки и
услуги, за да бъде тяхното количество в съответствие с желаното
от обществото.

### 2.3. Ограничения в конкуренцията

Ограниченията в конкуренцията и появата на монополни структури
могат да доведат до загуба на ефективност и намалено
благосъстояние, поради което може да е необходима държавна
намеса, изразяваща се в разбиването на монополната структура,
поставянето и под държавен контрол или регулирането на дейността
ѝ. Отношението на държавата към монополите беше разгледано в
Лекция 6 - "Конкуренция и пазарно поведение".

В същото време самата държавна намеса понякога е причина за
съществуването на монополи, когато държавната власт се използва
за извоюването и поддържането на благоприятни икономически
позиции.

### 2.4. Информационни ограничения 

Информационните ограничения са друга предпоставка за нарушаването
на ефективното действие на пазарния механизъм. Тя обикновено не е
проблем, когато размяната се осъществява веднага и характерът на
стоките е такъв, че има видими и лесно разпознаваеми показатели,
по които да се установи какво е тяхното качество. Например при
покупко-продажбата на плодове и зеленчуци в повечето случаи
купувачът е в състояние да прецени качеството им само по външния
вид и дали цената, по която се предлагат, съответства
на него. Дори в по-редките случаи, когато истинските качества на
плодовете и зеленчуците стават ясни едва след консумацията им,
цената на грешката е сравнително малка (защото стойността на
стоката е ниска и няма сериозни последици от самия акт на
консумацията). Ако потребителят е недоволен, просто няма да си
купи отново същите плодове и зеленчуци и действията му ще намерят
отражение в цените, които ще претърпят корекции, съответстващи на
реалното качество на стоката. 

Не така стоят нещата обаче със стоки или услуги, където купувачът
може да установи истинските им качества едва след като ги закупи
и при един по-продължителен период на експлоатация. Този проблем
се увеличава, колкото по-висока е стойността на стоката и колкото
по-диференцирани са продуктите (при хомогенните продукти е
по-лесно да се прецени какво е качеството на настоящия продукт на
база на информацията за другите продукти като него). Подобна
ситуация увеличава несигурността при сделките. Макар че в рамките
на пазара съществуват механизми, които предлагат частично решение
на този проблем (например репутационни механизми по отношение на
търговеца или продуктовата марка), не са редки случаите, когато
през политическия процес желанието за намаляване на тази
несигурност намира отражение в държавна намеса под формата на
регулиране на подобни дейности, например като се създаде
орган, който да контролира качеството на продуктите и да следи за
съответствие между декларираните и реалните им характеристики.

Най-силна тежест имат аргументите за държавна намеса при
информационни ограничения тогава, когато потребителите не са в
състояние да оценят качеството на предлаганите стоки или услуги
дори след употребата им, или когато цената на грешката и
последиците от неправилния избор са много големи. Обикновено
установяването на качеството на продукта изисква компетенции, с
които разполагат само хора, които предлагат продуктите, а тези
компетенции се придобиват след дълъг период на обучение и
квалификация. Пример за това са услугите, предлагани от лекари,
архитекти, адвокати и др. Необходимостта от държавна намеса е
много по-осеазаема, като понякога тя се изразява не толкова в
регулирането на предлагането на стоките и услугите директно, а в
осъществяването на контрол по качеството на входа в съответните
професии. 

## 3. Данъци и данъчна система

Данъкът е задължително и принудително плащане към държавата,
което възниква за стопанските субекти при настъпването на
определени събития. Условието за възникването на задължението са
предварително установени (например получаването на доход) и в
този смисъл то има регулярен характер. Данъците са основният,
макар и не единствен, източник на приходи за държавата. Освен
приходна, данъците имат и регулаторна функция, защото с тях може
да се влияе върху потреблението на конкретни стоки или услуги
(например цигари, алкохол и т.н.). Данъците могат да се използват
и за макроикономическо регулиране на стопанската активност в
националната икономика като цяло в качеството им на инструмент на
фискалната политика. Характерно за данъците е, че в повечето
случаи няма пряка връзка между размера на внесените данъци и
стойността на потребяваните обществени услуги на индивидуално
равнище. 

### Елементи на данъка

* предмет или обект на данъка - онова, което подлежи на данъчно
облагане (имущество, доход, печалба и т.н.).
* субект на данъка - физическо или юридическо лице, за което
възниква данъчното задължение. Лицето е в някаква форма на
отношение към обекта на данъка, например на собственост. Обикновено 
субектът на данъка е и негов носител, тоест понася неговата
тежест и плаща задължението. Възможно е обаче да са различни 
лица (например при косвените данъци).
* данъчен мащаб - характерна черта или белег на обекта на данъка,
на основата на който може да се определи неговият размер. Тъй
като данъците преобладаващо са парични, обикновено това са парични
единици. Възможно е обаче да e някакво физическо свойство,
например конски сили при автомобилите. 
* данъчна единица - конкретна и неизменна част от данъчния мащаб, 
която позволява измерване на данъчната основа.
* данъчна основа - броят на данъчните единици, които подлежат на
облагане. Обикновено това е паричната стойност на обекта на
данъка. Понякога данъчната основа е изразена в непарични единици,
като това зависи от възприетия данъчен мащаб - например броя на
конските сили на автомобила.
* данъчен размер или данъчна ставка - данъчното задължение, което
възниква върху една данъчна единица. Обикновено то е представено
като относителен дял в проценти или промили, когато данъчната
основа е изразена в парични единици. Когато данъчните единици са
физически обеми, може да бъде конкретна сума (например 1 лев на
10 конски сили). 
* данъчно задължение - сумата, която е дължима като данък
на държавата. Получава се, когато данъчната ставка (размер) се
наложи върху данъчната основа с умножаването на едното по друготo.

### Видове данъци

Следната категоризация на видовете няма претенции за
изчерпателност, но това са някои от най-важните критерии, според
които можем да ги групираме:

* според начина на облагане
    - преки - възникват за определени лица и са директно дължими от
тях, т.е. не могат да се прехвърлят. Такива са данък върху
доходите на физическите лица, корпоративният данък (данък
печалба). 
    - косвени - възникват за определени лица, но самото задължение
може да се прехвърли на някой друг. Това е възможно, защото тези
данъци са начислени в цените на стоките и услугите. У нас това са
данък добавена стойност, митата и акцизите.
* според равнището на на облагане
    - републикански - приходите от тях постъпват в републиканския
бюджет. Такива са ДДС, акцизите, митата, данък върху дохода на
физическите лица, корпоративния данък и др.
    - местни - приходите от тях постъпват в бюджета на местната
власт. Към настоящия момент тук се включват данъка върху
недвижимите имоти, данъка върху превозните средства, някои
патентни данъци.
* според тяхната прогресия (начина на тяхното определяне)
    - регресивни - с увеличаването на данъчната основа намалява
данъчната ставка.
    - пропорционални - данъчната ставка не се изменя при изменения
в данъчната основа. 
    - прогресивни - данъчната ставка се увеличава с увеличаването
на данъчната основа.

Особено спорове предизвикват данъците според начина на тяхното
определяне. В повечето страни скалата на облагане на доходите е
прогресивна. Страните с пропорционална данъчна скала са
малцинство и значителен дял от тях се намират в Източна Европа -
България, Румъния, Албания, Сърбия, Македония, Унгария, Босна и
Херцеговина, Русия и др. 

*Аргументите в полза на пропорционалното облагане* (т.нар. плосък
данък) са няколко. Първо, плоският данък е по-лесен за
администриране и създава по-малко трудности при подаването на
данъчните декларации. Второ, стимулите да се укриват по-високи
доходи са по-малки, защото данъчната ставка не се увеличава с
увеличаването на дохода. Това създава предпоставки за излизане на
една част от икономиката в сивия сектор "на светло". Трето, тъй
като данъчната ставка остава същата при повишаване на доходите,
това създава по-големи стимули за труд и е предпоставка за
повишаване на производството в национален мащаб. 

Основният *аргумент в подкрепа на прогресивното данъчно облагане*
на доходите е свързано с това, че всеки лев за хората с нисък
доход има много по-висока стойност, отколкото за хората с висок
доход. Плащането на един и същ дял от дохода би изисквало повече
жертви от хората с нисък, отколкото от хората с висок доход. За
първите това би означавало отказ от храна, отопление и други
предмети от първа необходимост, докато за вторите това би
означавало нов автомобил с по-малко екстри, например. Освен това
привържениците на прогресивното облагане оспорват валидността на
някои от аргументите в полза на плоския данък. Този който укрива
доход, за да не плаща данъци, ще продължи да го укрива,
независимо дали облагането на доходите е пропорционално или
прогресивно, освен ако не настъпят и други промени в
иснтитуционалната среда (например по-високи санкции за укриващите
данъци). Друг спорен момент е доколко плоският данък ще стимулира
предлагането на повече труд, тъй като големите различия в
заплащането идват от различията в характера на труда, не толкова
от времето, през което се работи.  

При изчисляването на данъчното задължение е важно да се прави
разграничение между средна данъчна ставкаи пределна данъчна
ставка. Нека имаме прогресивна данъчна скала, при която доходите
се облагат по следния начин:

      Доход		        Ставка
----------------- ----------------
до 2000 лв.	         0%
2001-4000 лв.		    5%
4001-6000 лв.		    10%
6001-8000 лв.		    15%
8001-10000 лв.		  20%
10000-15000 лв.		  25%
над 15000 лв.		    30%

Какво ще бъде данъчното задължение на човек с годишен доход от
20 000 хиляди лева? Няма да бъде 6 000 лева (30% от 20 000 лв.),
а $0\% \times 2000$ лв. (за първите 2000 лева) + $5\% \times 2000$ лв. (за
интервала 2001-4000 лв.) ... + $30\% \times 5000$ лв.(за парите между
15 000 и 20 000 лева), т.е. данъчното задължение ще бъде 3750
лева. Тогава средната данъчна ставка ще бъде 
$\frac{3750}{20000} \times 100\% = 18,75\%$. Пределната данъчна ставка е ставката
във всеки диапазон на дохода (например 25% за доход между 10 000
и 15 000 лева). Тези диапазони се наричат данъчни скоби или
данъчни етажи.

## 4. Основни въпроси и дискусии за ролята на държавата

Основният въпрос при дискусията за ролята на държавата в
икономиката е дали наличието на пазарни провали автоматично
оправдава държавната намеса. Не би било редно да сравняваме
несъвършеният пазар с един идеализиран образ на държавата.
Сравнението трябва да е между реални алтернативи, а не между
идеализирани типове. Ако държавата, в опитите си да компенсира
пазарните провали, също минава през такива, е редно да отчетем и
тях. 

Един от недостатъците на държавните институции и агенции е, че
обикновено разходите по издръжката им не са обвързани с
приходите, които реализират. Отсъстват достатъчно стимули за
оптимизиране на дейностите, защото финансирането им така или
иначе не зависи от тяхната ефективност. Понякога е по-важно
разходите да се оправдаят, отколкото да се оптимизират. Друг,
донякъде свързан с този проблем е, че целите на държавният орган
могат да влязат в противоречие с целите, които са поставени при
създаването му. Възможно е като приоритет да се оформи
продължаването на съществуването му или разширяването на
влиянието му, при което вместо да решава реално възникнали ,
съответната инстутиция може да решава проблеми, които сама
създава, за да оправдае съществуването си. Някои държавни
инстуции могат да бъдат "превзети" от групи по интереси, които
обслужват, а прокламираните дейности в полза на цялото
общество да остават само като параван. 

Пазарът позволява на хората да разкриват предпочитанията си само
дотолкова, доколкото доходът им го позволява. От тази гледна
точка електоралният процес на пръв поглед е по-справедлив, защото
всички са равнопоставени. Но тук се проявява друг проблем. При
гласуването всички гласове се броят еднакво, независимо каква е
силата на предпочитанията им. Ако някой е твърдо против изсичането
на дадена гора, неговият глас ще бъде неутрализиран от гласа на
някой друг, който е по-скоро за, без обаче да отдава особено
голямо значение на този въпрос. При пазарни условия, макар и да
са ограничени от платежоспособността си, хората в по-голяма
степен имат възможността да изразят интензитета на желанията си
като платят повече или по-малко за даден продукт. Като не се
отчита силата на предпочитанията, през електоралния процес могат
да се вземат неефективни от стопанска гледна точка решения.

Въпросът докъде трябва да се простира държавната намеса до голяма
степен стои отворен. Повечето икономисти са съгласни, че
държавата трябва да гарантира правата на собственост и спазването
на договорните задължения, както и да финансира обществените
блага. Оттам нататък обаче консенсус няма. Макар и малциноство,
някои икономисти смятат например, че държавата не трябва да 
се намесва дори при наличието на негативни външни ефекти и 
нарушения в свободната конкуренция. Техният глас не е решаващ, 
но показва, че проблемите са многопластови и по-сложни, отколкото 
изглеждат на пръв поглед. 



 


