title: "Фискална политика"
author: "Александър Косулиев"
date: "12.12.2015"
output: 
  pdf_document: 
    toc: yes
    toc_depth: 3
    latex_engine: xelatex
mainfont: Liberation Serif
sansfont: Liberation Sans
monofont: Liberation Mono
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(fig.width = 8, fig.height = 6,
                      fig.path = "figure/",
                      #dev='cairo_pdf',
                      echo = FALSE, warning = FALSE, 
                      message = FALSE)
```

## 1. Основни виждания за публичните финанси

### 1.1. Класическо виждане за публичните финанси

Виждането на представителите на класическата икономическа школа
е, че държавния бюджет трябва да бъде *балансиран* и *сдържан*.

__Балансираността на бюджета__ означава, че приходите и разходите
трябва да са приблизително равни. Когато разходите превишават
приходите е налице бюджетен дефицит, който трябва да се финансира
по някакъв начин. Една от възможностите е да се използват
натрупаните средства във фиксалния резерв, но продължителното
реализиране на дефицити неминуемо води до необходимостта от
финансирането им със заеми. Така политиката на бюджетни дефицити
е свързана с увеличаването на държавния дълг. Тъй като
обслужването на дълга може да създаде проблеми за самото
правителство и за националната икономика като цяло (за това ще
стане дума по-нататък), е препоръчително дефицитите да се
избягват. 

Когато приходите превишават разходите имаме бюджетен излишък.
Тази част, с която приходите превишават разходите, позволява да
се попълва фискалния резерв на държавата, който може да се
използва в случай на нужда при появата на непредвидени разходи.
Макар че е по-добре в бюджета да има излишъци, отколкото
дефицити, продължителното формиране на големи излишъци също не е
добра тенденция. Това означава, че държавата системно
изземва от населението повече, отколкото е необходимо, с което
лишава стопанските агенти от възможността да използват тези
средства по собствено усмотрение. 

Затова според класическите икономисти добрият бюджет е
балансираният бюджет или бюджет с малки излишъци.

__Сдържаността на бюджета__ означава, че балансираността трябва
да се осъществява на едно ниско равнище на държавните разходи.
Възможно е големите държавни разходи да се покрият от голям
размер на приходите, но според класическите икономисти държавата
трябва да ограничи разходите си до такова ниво, което осигурява
средства за основните функции на държавата, които позволяват
безпроблемното действие на пазарния механизъм. Тоест, от бюджета
трябва да се финансират законодателната и изпълнителната власт,
както и правоохранителните и правораздавателните органи - армия,
съд, полиция, прокуратура. Когато те функционират както трябва,
правата на собственост са защитени и се гарантира спазването на
договорните задължения, което е предпоставка за съществуването на
една пазарна икономика. 

Защо класическите икономисти са против натрупването на държавен
дълг? 

* Когато дългът е висок, обслужването му може да наложи
орязване на държавните разходи дори отвъд санитарния минимум,
който осигурява безпроблемното функциониране на пазара. 
* Друг вариант е да се увеличат данъците, но това ще намали
стимулите за частна инициатива и ще доведе до по-слаба
икономическа активност.  
* Високите нива на задлъжнялост обикновено водят да повишаване на
лихвените проценти, което отразява риска от прекратяване на
обслужването на дълга. Колкото по-висок е дългът, толкова
по-вероятно е всяко следващо правителство да откаже да прави
плащания по него с мотива, че задълженията са натрупани от
техните политически противници и те не носят отговорност за
действията на предишните управляващи.  Несигурността по отношение
на държавните финанси може да се пренесе на финансовите пазари в
страната.  По-високите лихвени проценти затрудняват достъпа до
заемни средства за фирмите и гражданите и също намаляват
икономическата активност. 
* Високите нива на задлъжнялост създават очаквания за инфлация,
особено когато централната банка е под контрола на
правителството. В ролята си на голям длъжник, правителството има
интерес от това да заработи "печатницата за пари", с което
реалната стойност на дълга ще намалее. Очакванията за висока
инфлация също създават несигурност в стопанската среда и оказват
негативно влияние върху икономическата активност.

### 1.2. Кейнсианско виждане за публичните финанси

Икономисти като Джон Мейнард Кейнс и неговите последователи имат
друго разбиране за държавния бюджет. Според тях балансираността
на бюджета идва на определена цена, която не винаги си заслужава
да бъде платена. По време на криза икономическата активност
намалява, при което спадат приходите в бюджета. За да го
балансира, държавата трябва да намали разходите. Но намаляването
на разходите на правителството при една и без това навлязла в
криза икономика, ще доведе до допълнително свиване на съвкупното
търсене и допълнителни проблеми за фирмите да намерят реализация
на продукцията си, които и без това вече срещат достатъчно
трудности. Това ще намали допълнително производството и заетостта
и ще предизвика задълбочаване на кризата и ще я направи
по-продължителна. 

Според кейнсианците по време на криза правителството не трябва да
се стреми към балансиран бюджет, а напротив - да увеличава
разходите, дори това да означава по-големи дефицити. Но тези
по-големи дефицити стимулират съвкупното търсене и са
предпоставка за по-бързото излизане от кризата. Колкото по-бързо
националната икономика излезе от кризата, толкова по-лесно ще
може да се балансира бюджета. С подобряването на икономическата
активност необходимостта от поддържане на големи държавни разходи
за стимулиране на съвкупното търсене намалява, а в същото време
приходите от данъци се увеличават. Така в периоди на оживление и
подем правителството може не просто да поддържа балансиран
бюджет, а да реализира бюджетни излишъци. С излишъците по време
на възходящите фази на стопанския цикъл то може да финансира
дефицитите по време на криза. Така едновременно се стимулира
икономиката и се избягва трупането на държавен дълг.

Според кейнсианците е грешно балансирането на бюджета в рамките
на една календарна година да се поставя като самоцел.
Астрономическото време има малко общо с икономическата активност
и не трябва да служи като критерий за периода на балансиране на
бюджета. Националното стопанство има свой собствен пулс и ритъм и
ръководейки се от него, икономическата логика предполага бюджетът
да се балансира в рамките на стопанския цикъл, а не на
календарната година.

Ако трябва да обобощим кейнсианското виждане, те разглеждат
бюджета като инструмент, с който можем да повлияем върху фазите
на стопанския цикъл. Това са т.нар. *функционални
финанси*. Провеждането на фискална политика предполага наличието
на функционални финанси. __Фискалната политика__ е процес на
формирането на приходите и разходите в държавния бюджет с цел
постигането и поддържането на икономически растеж, висока заетост
и ценова стабилност. Не всички приходи и разходи в бюджета са
проява на фискална политика. Класическото разбиране за държавните
финанси също предполага приходи и разходи в бюджета, но те нямат
като непосредствена цел заетостта и растежа. Те са необходими
дотолкова, доколкото осигуряват функционирането на пазара. А
пазарът сам се грижи за всичко останало. Например разходите за
съдебната власт се правят независимо дали икономиката е в криза
или подем. Фискалната политика предполага използването на бюджета
за изглаждането на фазите на стопанския цикъл, което е
несъвместимо с класическото и съвпада с кейнсианското разбиране
на обществените финанси.

## 2. Инструменти на фискалната политика

* Инструменти, които влияят върху съвкупното търсене
  - държавни разходи (G). 
  - данъци (Т)

* Инструменти, които влияят върху съвкупното предлагане
  - субсидии
  - данъци (Т)

## 3. Видове фискална политика

* Експанзионистична политика - може да бъде насочена както към
стимулиране на съвкупното търсене (AD), така и към стимулиране на
краткосрочното съвкупно предлагане (SAS). Провежда се по време на
рецесионен разрив (т.е. при рецесия). Целта е да се стимулира
икономическата активност и да се постигне макроикономическо
равновесие при пълна заетост. Осъществява се като се увеличат
правителствените разходи и субсидии и се намалят данъците.

* Рестриктивна политика - насочена е главно към ограничаване на
съвкупното търсене (AD). Провежда се при инфлационен разрив (т.е.
при "прегряване" на икономиката), когато прекалено голямото
съвкупно търсене при пълна заетост създава предпоставки за
покачване в общото ценово равнище. Осъществява се като се намалят
правителствените разходи и се повишат данъците.

## 4. Ограничения пред фискалната политика

* Изтласкващ ефект - когато държавните инвестиции изтласкат
частните инвестиции от пазара. Проявява се чрез увеличението на
лихвения процент.

* Компенсиращ ефект - когато увеличените правителствени разходи
са съпътствани от намалени разходи на домакинствата. Може да се
наблюдава, когато повишението на правителствените разходи се
финансира с увеличаване на данъците. Възможно е обаче да се
получи и когато правителството финансира повишените си разходи
със заеми.

* Лагове на фискалната политка - идентифицирането на проблема,
вземането на решение какво да се прави, привеждането на мерките в
действие и появата на ефективността от мерките отнемат време.
През това време възникналия проблем вероятно вече е отминал от
само себе си.

