---
title: "Лекция 5. Разходи и приходи на фирмата" 
author: "Александър Косулиев"
date: "10.10.2015"
output: html_document
---

```{r global_options, include = FALSE}
knitr::opts_chunk$set(fig.width = 8, fig.height = 6,
                      fig.path = "figure/",
                      echo = FALSE, warning = FALSE, 
                      message = FALSE)
```



| L     | TP    | FC     | VC      | TC      |
|------:|------:|-------:|--------:|--------:|
| 1.00  | 5.00  | 100.00 | 95.00   | 195.00  |
| 2.00  | 11.00 | 100.00 | 205.00  | 305.00  |
| 3.00  | 18.00 | 100.00 | 330.00  | 430.00  |
| 4.00  | 32.00 | 100.00 | 560.00  | 660.00  |
| 5.00  | 50.00 | 100.00 | 850.00  | 950.00  |
| 6.00  | 68.00 | 100.00 | 1140.00 | 1240.00 |
| 7.00  | 77.00 | 100.00 | 1295.00 | 1395.00 |
| 8.00  | 80.00 | 100.00 | 1360.00 | 1460.00 |
| 9.00  | 82.00 | 100.00 | 1410.00 | 1510.00 |
| 10.00 | 83.00 | 100.00 | 1445.00 | 1545.00 |

```{r fc_vc_tc}
plot(x = c(0, prcompDF$TP), y = c(100, prcompDF$TC), 
     type = "o", pch = 20,
     lwd = 2, xaxs = "i", yaxs = "i", bty = "n",
     xlim = c(0,100), ylim = c(0,1620), 
     xlab = "Количество, бр.", ylab = "Разходи, лв.",
     main = "Постоянни, променливи и общи разходи")
grid()
lines(x = c(0, prcompDF$TP), y = c(100, prcompDF$FC), 
      lwd = 2, type = "o", pch = 20)
text(87,50, "FC")
text(87,822.5, "VC")
text(87, 1600, "TC=FC+VC")
rect(0,0,83,100, col = adjustcolor("orange", alpha.f = 0.3), 
     border = "transparent")
polygon(c(0,prcompDF$TP,rev(prcompDF$TP),0), 
	c(100,prcompDF$TC,rep(100, length(prcompDF$TC)+1)),
	col = adjustcolor("yellow", alpha.f = 0.3), 
	border = "transparent")

```

```{r product-cost-relation, fig.width = 6, fig.height = 8}
par(mfrow = c(2,1), mar = c(3,4,3,1))
plot(x = prcompDF$L, y = prcompDF$AP, bty = "n",
     type = "o", pch = 20, lwd = 2, col = "red",
     xaxs = "i", yaxs = "i", 
     xlim = c(0,11), ylim = c(0,20), 
     xlab = "", ylab = "Среден и пределен продукт",
     main = "Средни и пределни продукт и разходи")
grid()
mtext("Работници, бр.", side = 1, line = 2)
lines(x = prcompDF$L, y = prcompDF$MP, lwd = 2, type = "o", pch = 20, col = "darkred")
text(10.5,8.3, "AP")
text(10.5,1, "MP")
rect(0,0,5,20, col = adjustcolor("green", alpha.f = 0.1), border = "transparent")
rect(5,0,6,20, col = adjustcolor("yellow", alpha.f = 0.1), border = "transparent")
rect(6,0,10,20, col = adjustcolor("red", alpha.f = 0.1), border = "transparent")
plot(x = prcompDF$L, y = prcompDF$ATC, bty = "n",
     type = "o", pch = 20, lwd = 2, col = "red",
     xaxs = "i", yaxs = "i", 
     xlim = c(0,11), ylim = c(0,45), 
     xlab = "", ylab = "Средни и пределни разходи")
grid()
lines(x = prcompDF$L, y = prcompDF$MC, lwd = 2, type = "o", pch = 20, col = "darkred")
axis(3, at = 0:10, labels = c(0, prcompDF$TP), lty = 2, 
     outer = FALSE, cex.axis = 0.7, padj = 1, tcl = -0.5, line = -1)
mtext("Общ продукт, бр.", side = 3, line = 1, cex = 0.7)
mtext("Работници, бр.", side = 1, line = 2)
text(10.5,18.61, "ATC")
text(10.5,35, "MC")
rect(0,0,5,39, col = adjustcolor("green", alpha.f = 0.1), border = "transparent")
rect(5,0,6,39, col = adjustcolor("yellow", alpha.f = 0.1), border = "transparent")
rect(6,0,10,39, col = adjustcolor("red", alpha.f = 0.1), border = "transparent")

```

```{r afc-avc-atc}
plot(x = prcompDF$TP, y = prcompDF$ATC, 
     type = "o", lwd = 2, col = "red", pch = 20, 
     xaxs = "i", yaxs = "i", xlim = c(0,115), ylim = c(0,40),
     bty = "n", xlab = "Количество, бр.", ylab = "Разходи",
     main = "Средни разходи")
grid()
lines(x = prcompDF$TP, y = prcompDF$AVC, type = "o", lwd = 2,
      pch = 20, col = "darkorange")
lines(x = prcompDF$TP, y = prcompDF$AFC, type = "o", lwd = 2,
      pch = 20, col = "yellow")
text(87,18.61, "ATC=AFC+AVC", adj = 0)
text(87,17.41, "AVC", adj = 0)
text(87,1.2, "AFC", adj = 0)

```

|  работник  |  от кг  |  до кг  |  MC   |
|-----------:|--------:|--------:|------:|
| 1          | 1       | 5       | 39.00 |
| 2          | 6       | 11      | 18.33 |
| 3          | 12      | 18      | 17.86 |
| 4          | 19      | 32      | 16.43 |
| 5          | 33      | 50      | 16.11 |
| 6          | 51      | 68      | 16.11 |
| 7          | 69      | 77      | 17.22 |
| 8          | 78      | 80      | 21.67 |
| 9          | 81      | 82      | 25.00 |
| 10         | 83      | 83      | 35.00 |





```{r mc-only}

# create a vector for MC that shows it as intervals
mcinterval <- rep(prcompDF$MC, each = 2)
mcinterval
# create the corresponding vector for TP
prcompDF$TP
temp1 <- as.vector(rep(0, length(prcompDF$TP)))
for (i in 2:length(temp1)) {temp1[i] <- prcompDF$TP[i-1]}
temp1
tpinterval <- as.vector(rep(0, 2*length(temp1)))
for (i in 1:length(temp1)) {
	tpinterval[2*i-1] <- temp1[i] + 1
	tpinterval[2*i] <- prcompDF$TP[i]
}
# create a dataframe for plotting that combines them and
# add price at 20 and 25 leva
mcintervalgraphDF <- data.frame(tpinterval, mcinterval, rep(20, length(mcinterval)), rep(25, length(mcinterval)))
colnames(mcintervalgraphDF) <- c("TP","MC","MR1","MR2")
# A graph that shows MC as intervals
plot(x = mcintervalgraphDF$TP, y = mcintervalgraphDF$MC,
     xaxs = "i", yaxs = "i", xlim = c(0,85), ylim = c(10,40),
     xlab = "Продукция, бр.", ylab = "Пределни разходи, лв.",
     type = "o", lwd = 2, col = "darkred", pch = 20, 
     bty = "n", main = "Представяне на пределните разходи")
grid()
lines(x = prcompDF$TP, y = prcompDF$MC, type = "l", 
      col = "red", lty = 2)
arrows(1.3,38,4.6,38, code = 3, length = 0.05, angle = 15)
text(2.8,37, "39\nлв/ед.", cex = 0.7)
arrows(19.3,15.43,31.7,15.43, code = 3, length = 0.05, angle = 15) 
text(25.5,14.43, "от 19 до 32 ед.\n - по 16.43 лв/ед.", cex = 0.7)
arrows(12.3,16.86,17.7,16.86, code = 3, length = 0.05, angle = 15)
text(15,15.86, "17.86\nлв/ед.", cex = 0.7)
arrows(6.3,17.33,10.7,17.33, code = 3, length = 0.05, angle = 15)
text(8.5,16.33, "18.33\nлв/ед.", cex = 0.7)
arrows(33.3,15.11,49.7,15.11, code = 3, length = 0.05, angle = 15)
text(41.5,14.11, "от 33 до 50 ед.\n - по 16.11 лв/ед.", cex = 0.7)
arrows(51.3,15.11,67.7,15.11, code = 3, length = 0.05, angle = 15)
text(59.5,14.11, "от 51 до 68 ед.\n - по 16.11 лв/ед.", cex = 0.7)
arrows(69.3,16.22,76.7,16.22, code = 3, length = 0.05, angle = 15)
text(73,15.22, "17.22\nлв/ед.", cex = 0.7)

```

| L     | TP     | MP    | AP    | FC     | VC      | TC      | AFC   | AVC   | ATC   | MC    |
|-------|--------|-------|-------|--------|---------|---------|-------|-------|-------|-------|
| 1.00  | 5.00   | 5.00  | 5.00  | 140.00 | 95.00   | 235.00  | 28.00 | 19.00 | 47.00 | 47.00 |
| 2.00  | 11.00  | 6.00  | 5.50  | 140.00 | 205.00  | 345.00  | 12.73 | 18.64 | 31.36 | 18.33 |
| 3.00  | 18.00  | 7.00  | 6.00  | 140.00 | 330.00  | 470.00  | 7.78  | 18.33 | 26.11 | 17.86 |
| 4.00  | 32.00  | 14.00 | 8.00  | 140.00 | 560.00  | 700.00  | 4.38  | 17.50 | 21.88 | 16.43 |
| 5.00  | 50.00  | 18.00 | 10.00 | 140.00 | 850.00  | 990.00  | 2.80  | 17.00 | 19.80 | 16.11 |
| 6.00  | 70.00  | 20.00 | 11.67 | 140.00 | 1170.00 | 1310.00 | 2.00  | 16.71 | 18.71 | 16.00 |
| 7.00  | 93.00  | 23.00 | 13.29 | 140.00 | 1535.00 | 1675.00 | 1.51  | 16.51 | 18.01 | 15.87 |
| 8.00  | 116.00 | 23.00 | 14.50 | 140.00 | 1900.00 | 2040.00 | 1.21  | 16.38 | 17.59 | 15.87 |
| 9.00  | 132.00 | 16.00 | 14.67 | 140.00 | 2160.00 | 2300.00 | 1.06  | 16.36 | 17.42 | 16.25 |
| 10.00 | 142.00 | 10.00 | 14.20 | 140.00 | 2330.00 | 2470.00 | 0.99  | 16.41 | 17.39 | 17.00 |
| 11.00 | 147.00 | 5.00  | 13.36 | 140.00 | 2425.00 | 2565.00 | 0.95  | 16.50 | 17.45 | 19.00 |
| 12.00 | 150.00 | 3.00  | 12.50 | 140.00 | 2490.00 | 2630.00 | 0.93  | 16.60 | 17.53 | 21.67 |
| 13.00 | 152.00 | 2.00  | 11.69 | 140.00 | 2540.00 | 2680.00 | 0.92  | 16.71 | 17.63 | 25.00 |
| 14.00 | 153.00 | 1.00  | 10.93 | 140.00 | 2575.00 | 2715.00 | 0.92  | 16.83 | 17.75 | 35.00 |


``` {r long-term-ac}
plot(xlim = c(0,340), ylim = c(0,50),
     xaxs = "i", yaxs = "i", bty = "n",
     x = 1:10, y = 1:10, type = "n",
     xaxt = "n",
     xlab = "Обща продукция, бр.", ylab = "Разходи, лв.",
     main = "Средни краткосрочни и дългосрочни разходи")
axis(side = 1, at = c(0,20,40,60,80,100,120,140,160,180,200,220,240,260,280,300,340))
grid()
curve((1/8*x-10)^2 + 21.50, add = TRUE, 
      from = 50, to = 110, lwd = 2, col = "red")
curve((1/8*x-15)^2 + 16.7, add = TRUE, 
       from = 90, to = 150, lwd = 2, col = "darkorange")
curve((1/8*x-20)^2 + 15, add = TRUE,
      from = 130, to = 190, lwd = 2, col = "red")
curve((1/8*x-25)^2 + 16.7, add = TRUE,
      from = 170, to = 230, lwd = 2, col = "darkorange")
curve((1/8*x-30)^2 + 21.50, add = TRUE,
      from = 210, to = 270, lwd = 2, col = "red")
curve((1/32*x-5)^2 + 15, add = TRUE,
      from = 10, to = 310, lwd = 2, col = "darkred")
text(110,(21.5+16), expression("SAC"[1]), cex = 0.7)
text(150,(16.7+16), expression("SAC"[2]), cex = 0.7)
text(190,(15+16), expression("SAC"[3]), cex = 0.7)
text(230,(16.7+16), expression("SAC"[4]), cex = 0.7)
text(270,(21.5+16), expression("SAC"[5]), cex = 0.7)
text(310,40, "LAC", cex = 0.7)
segments(132,0,132,27.24, lty = 2, col = "blue")
segments(148,0,148,28.95, lty = 2, col = "green")
# При 132 бройка - AC2 = 18.95 лв. и AC3 = 27.25 лв.
# При 148 бройка - AC2 = 28.95 лв. и AC3 = 17.25 лв.

```



| L     | TP    | P=AR  | TR      | MR    |
|-------|-------|-------|---------|-------|
| 1.00  | 5.00  | 20.00 | 100.00  | 20.00 |
| 2.00  | 11.00 | 20.00 | 220.00  | 20.00 |
| 3.00  | 18.00 | 20.00 | 360.00  | 20.00 |
| 4.00  | 32.00 | 20.00 | 640.00  | 20.00 |
| 5.00  | 50.00 | 20.00 | 1000.00 | 20.00 |
| 6.00  | 68.00 | 20.00 | 1360.00 | 20.00 |
| 7.00  | 77.00 | 20.00 | 1540.00 | 20.00 |
| 8.00  | 80.00 | 20.00 | 1600.00 | 20.00 |
| 9.00  | 82.00 | 20.00 | 1640.00 | 20.00 |
| 10.00 | 83.00 | 20.00 | 1660.00 | 20.00 |



|  работник  |  от кг  |  до кг  |  MC   |  MR  |  резултат от кг  |  резултат в интервала  |  общ резултат    | 
|-----------:|--------:|--------:|------:|-----:|-----------------:|-----------------------:|-----------------:| 
| 1          | 1       | 5       | 39.00 | 20   | -19.00           | -95                    | -95              | 
| 2          | 6       | 11      | 18.33 | 20   | 1.67             | 10                     | -85              | 
| 3          | 12      | 18      | 17.86 | 20   | 2.14             | 15                     | -70              | 
| 4          | 19      | 32      | 16.43 | 20   | 3.57             | 50                     | -20              | 
| 5          | 33      | 50      | 16.11 | 20   | 3.89             | 70                     | 50               | 
| 6          | 51      | 68      | 16.11 | 20   | 3.89             | 70                     | 120              | 
| 7          | 69      | 77      | 17.22 | 20   | 2.78             | 25                     | 145              | 
| 8          | 78      | 80      | 21.67 | 20   | -1.67            | -5                     | 140              | 
| 9          | 81      | 82      | 25.00 | 20   | -5.00            | -10                    | 130              | 
| 10         | 83      | 83      | 35.00 | 20   | -15.00           | -15                    | 115              | 















```{r max-profit-pc, fig.width=12, fig.height=6}
par(mfrow = c(1,2))
plot(x = mcintervalgraphDF$TP, y = mcintervalgraphDF$MC,
     xaxs = "i", yaxs = "i", xlim = c(0,100), ylim = c(10,40),
     xlab = "Продукция, бр.", ylab = "Разходи и приходи, лв.",
     type = "o", lwd = 2, col = "darkred", pch = 20, 
     bty = "n", main = "Максимална печалба")
grid(nx=10)
#lines(x = prcompDF$TP, y = prcompDF$MC, type = "l", 
#      col = "red", lty = 2)
lines(x = prcompDF$TP, y = prcompDF$ATC, type = "o", 
      col = "red", lwd = 2, pch = 20)
lines(x = c(0,prcompDF$TP), y = c(20,prcompDF$MR), type = "o",
      col = "darkblue", lwd = 2, pch = 20)
text(87,18.61, "ATC", adj = 0)
text(87,35, "MC", adj = 0)
text(87,20, "P=MR", adj = 0)
rect(0,0,77,18.12, col = adjustcolor("red", alpha.f = 0.1),
     border = "transparent")
rect(0,18.12,77,20, col = adjustcolor("green", alpha.f = 0.1),
     border = "transparent")
plot(x = mcintervalgraphDF$TP, y = mcintervalgraphDF$MC,
     xaxs = "i", yaxs = "i", xlim = c(0,100), ylim = c(10,40),
     xlab = "Продукция, бр.", ylab = "Разходи и приходи, лв.",
     type = "o", lwd = 2, col = "darkred", pch = 20, 
     bty = "n", main = "Печалба при най-ниски\nпределни разходи")
grid(nx=10)
#lines(x = prcompDF$TP, y = prcompDF$MC, type = "l", 
#      col = "red", lty = 2)
lines(x = prcompDF$TP, y = prcompDF$ATC, type = "o", 
      col = "red", lwd = 2, pch = 20)
lines(x = c(0,prcompDF$TP), y = c(20,prcompDF$MR), type = "o",
      col = "darkblue", lwd = 2, pch = 20)
text(87,18.61, "ATC", adj = 0)
text(87,35, "MC", adj = 0)
text(87,20, "P=MR", adj = 0)
rect(0,0,50,19, col = adjustcolor("red", alpha.f = 0.1),
     border = "transparent")
rect(0,19,50,20, col = adjustcolor("green", alpha.f = 0.1),
     border = "transparent")
```

```{r max-profit-pri-25-lw, fig.width=12, fig.height=6}
par(mfrow = c(1,2))
plot(x = mcintervalgraphDF$TP, y = mcintervalgraphDF$MC,
     xaxs = "i", yaxs = "i", xlim = c(0,100), ylim = c(10,40),
     xlab = "Продукция, бр.", ylab = "Разходи и приходи, лв.",
     type = "o", lwd = 2, col = "darkred", pch = 20, 
     bty = "n", main = "Максимална печалба\nпри цена 20 лв.")
grid(nx=10)
#lines(x = prcompDF$TP, y = prcompDF$MC, type = "l", 
#      col = "red", lty = 2)
lines(x = prcompDF$TP, y = prcompDF$ATC, type = "o", 
      col = "red", lwd = 2, pch = 20)
lines(x = c(0,prcompDF$TP), y = c(20,prcompDF$MR), type = "o",
      col = "darkblue", lwd = 2, pch = 20)
text(87,18.61, "ATC", adj = 0)
text(87,35, "MC", adj = 0)
text(87,20, "P=MR", adj = 0)
rect(0,0,77,18.12, col = adjustcolor("red", alpha.f = 0.1),
     border = "transparent")
rect(0,18.12,77,20, col = adjustcolor("green", alpha.f = 0.1),
     border = "transparent")
plot(x = mcintervalgraphDF$TP, y = mcintervalgraphDF$MC,
     xaxs = "i", yaxs = "i", xlim = c(0,100), ylim = c(10,40),
     xlab = "Продукция, бр.", ylab = "Разходи и приходи, лв.",
     type = "o", lwd = 2, col = "darkred", pch = 20, 
     bty = "n", main = "Максимална печалба\nпри цена 25 лв.")
grid(nx=10)
#lines(x = prcompDF$TP, y = prcompDF$MC, type = "l", 
#      col = "red", lty = 2)
lines(x = prcompDF$TP, y = prcompDF$ATC, type = "o", 
      col = "red", lwd = 2, pch = 20)
lines(x = c(0,prcompDF$TP), y = c(25,prcompDF$MR2), type = "o",
      col = "darkblue", lwd = 2, pch = 20)
text(87,18.61, "ATC", adj = 0)
text(87,35, "MC", adj = 0)
text(87,25, "P=MR", adj = 0)
rect(0,0,80,18.25, col = adjustcolor("red", alpha.f = 0.1),
     border = "transparent")
rect(0,18.25,80,25, col = adjustcolor("green", alpha.f = 0.1),
     border = "transparent")

```
